[general]
import = ["./tokyo-night.toml"]

[env]
TERM = "xterm-256color"
LANG = "en_IN"

[window]
padding = { x = 12, y = 12 }
dimensions = { columns = 104, lines = 26 }
opacity = 0.92
blur = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
size = 10

[cursor]
style = { shape = "Underline", blinking = "Always" }

[keyboard]
bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" },
]

